dist: trusty
sudo: required
language: c
cache:
  apt: true
  directories:
  - $HOME/.opam
  - $HOME/bin

addons:
  apt:
    sources:
      - avsm

env:
  global:
    - NJOBS=2
    - COMPILER="4.11.1"
    - NATIVE_COMP="yes"
    - COQ_VER="8.12.0"
    - DUNE_VER="2.7.0"
    - CMDLINER_VER="1.0.4"
    - SIMPLE_IO_VER="1.3.0"
    - OPAMVERBOSE=3

install:
  - curl -sL https://raw.githubusercontent.com/ocaml/opam/master/shell/install.sh > install.sh
  - export PATH=$HOME/bin:$PATH
  - which opam || (rm -rf $HOME/.opam; echo $HOME/bin | sudo sh install.sh --no-backup; opam init --disable-sandboxing -j ${NJOBS} --compiler=${COMPILER} -n -y)
  - opam --version
  - eval $(opam config env)
  - opam config list
  - opam repo add coq-released https://coq.inria.fr/opam/released || true
  - opam update
  - opam install -j ${NJOBS} -y cmdliner.${CMDLINER_VER} dune.${DUNE_VER} coq.${COQ_VER} coq-simple-io.${SIMPLE_IO_VER}
  - opam list

script:
  - ./src-prepare.sh
  - dune build